from flask import Flask, jsonify



app = Flask(__name__)

data = [
  {
    "id": 1,
    "quantita": 3,
    "locazione": "",
    "prezzo": 250000,
    "metri_quadri": 120,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2015,
    "condominio": True,
    "piano": 2,
    "ascensore": True,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento moderno in ottime condizioni.",
    "foto": "url_foto_1.jpg"
  },
  {
    "id": 2,
    "quantita": 2,
    "locazione": "    ",
    "prezzo": 300000,
    "metri_quadri": 80,
    "tipo": "Monolocale",
    "numero_stanze": 1,
    "bagni": 1,
    "balcone": False,
    "anno_costruzione": 2020,
    "condominio": True,
    "piano": 5,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Angolo cottura",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Monolocale luminoso con vista.",
    "foto": "url_foto_2.jpg"
  },
  {
    "id": 3,
    "quantita": 1,
    "locazione": None,
    "prezzo": 200000,
    "metri_quadri": 90,
    "tipo": "Appartamento",
    "numero_stanze": 3,
    "bagni": 1,
    "balcone": True,
    "anno_costruzione": 2010,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": False,
    "cucina": "Abitabile",
    "posto_auto": True,
    "giardino": True,
    "descrizione": "Appartamento con giardino privato.",
    "foto": "url_foto_3.jpg"
  },
  {
    "id": 4,
    "quantita": 4,
    "locazione": "Torino",
    "prezzo": 280000,
    "metri_quadri": 110,
    "tipo": "Appartamento",
    "numero_stanze": 5,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2018,
    "condominio": True,
    "piano": 3,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Ampio appartamento in zona centrale.",
    "foto": "url_foto_4.jpg"
  },
  {
    "id": 5,
    "quantita": 5,
    "locazione": "Bologna",
    "prezzo": 320000,
    "metri_quadri": 150,
    "tipo": "Villa",
    "numero_stanze": 6,
    "bagni": 3,
    "balcone": True,
    "anno_costruzione": 2019,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": True,
    "descrizione": "Villa con ampio giardino.",
    "foto": "url_foto_5.jpg"
  },
  {
    "id": 6,
    "quantita": 3,
    "locazione": "Firenze",
    "prezzo": 290000,
    "metri_quadri": 100,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2016,
    "condominio": True,
    "piano": 2,
    "ascensore": True,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento in centro con servizi vicini.",
    "foto": "url_foto_6.jpg"
  },
  {
    "id": 7,
    "quantita": 1,
    "locazione": "Verona",
    "prezzo": 270000,
    "metri_quadri": 85,
    "tipo": "Appartamento",
    "numero_stanze": 3,
    "bagni": 1,
    "balcone": False,
    "anno_costruzione": 2021,
    "condominio": True,
    "piano": 4,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": False,
    "cucina": "Angolo cottura",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Appartamento nuovo in zona tranquilla.",
    "foto": "url_foto_7.jpg"
  },
  {
    "id": 8,
    "quantita": 2,
    "locazione": "Genova",
    "prezzo": 310000,
    "metri_quadri": 120,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2014,
    "condominio": True,
    "piano": 3,
    "ascensore": True,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento con vista mare.",
    "foto": "url_foto_8.jpg"
  },
  {
    "id": 9,
    "quantita": 4,
    "locazione": "Palermo",
    "prezzo": 230000,
    "metri_quadri": 95,
    "tipo": "Appartamento",
    "numero_stanze": 3,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2012,
    "condominio": True,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": False,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento in zona residenziale.",
    "foto": "url_foto_9.jpg"
  },
  {
    "id": 10,
    "quantita": 5,
    "locazione": "Catania",
    "prezzo": 260000,
    "metri_quadri": 115,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2017,
    "condominio": True,
    "piano": 2,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": True,
    "descrizione": "Appartamento spazioso con giardino.",
    "foto": "url_foto_10.jpg"
  },
  {
    "id": 11,
    "quantita": 3,
    "locazione": "Napoli",
    "prezzo": 220000,
    "metri_quadri": 105,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 1,
    "balcone": False,
    "anno_costruzione": 2011,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": False,
    "cucina": "Angolo cottura",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento con ampi spazi.",
    "foto": "url_foto_11.jpg"
  },
  {
    "id": 12,
    "quantita": 2,
    "locazione": "Milano",
    "prezzo": 340000,
    "metri_quadri": 140,
    "tipo": "Appartamento",
    "numero_stanze": 5,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2020,
    "condominio": True,
    "piano": 5,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Ampio appartamento in centro città.",
    "foto": "url_foto_12.jpg"
  },
  {
    "id": 13,
    "quantita": 3,
    "locazione": "Torino",
    "prezzo": 310000,
    "metri_quadri": 125,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2016,
    "condominio": True,
    "piano": 3,
    "ascensore": True,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento con vista sulla città.",
    "foto": "url_foto_13.jpg"
  },
  {
    "id": 14,
    "quantita": 1,
    "locazione": "Firenze",
    "prezzo": 280000,
    "metri_quadri": 95,
    "tipo": "Monolocale",
    "numero_stanze": 1,
    "bagni": 1,
    "balcone": False,
    "anno_costruzione": 2019,
    "condominio": True,
    "piano": 2,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Angolo cottura",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Monolocale moderno vicino al centro.",
    "foto": "url_foto_14.jpg"
  },
  {
    "id": 15,
    "quantita": 2,
    "locazione": "Bologna",
    "prezzo": 250000,
    "metri_quadri": 90,
    "tipo": "Appartamento",
    "numero_stanze": 3,
    "bagni": 1,
    "balcone": True,
    "anno_costruzione": 2021,
    "condominio": True,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": False,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": True,
    "descrizione": "Appartamento con giardino in una zona tranquilla.",
    "foto": "url_foto_15.jpg"
  },
  {
    "id": 16,
    "quantita": 4,
    "locazione": "Catania",
    "prezzo": 300000,
    "metri_quadri": 130,
    "tipo": "Villa",
    "numero_stanze": 5,
    "bagni": 3,
    "balcone": True,
    "anno_costruzione": 2015,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": True,
    "descrizione": "Villa con piscina privata.",
    "foto": "url_foto_16.jpg"
  },
  {
    "id": 17,
    "quantita": 1,
    "locazione": "Palermo",
    "prezzo": 210000,
    "metri_quadri": 85,
    "tipo": "Appartamento",
    "numero_stanze": 2,
    "bagni": 1,
    "balcone": False,
    "anno_costruzione": 2020,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": False,
    "cucina": "Angolo cottura",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento con vista sul mare.",
    "foto": "url_foto_17.jpg"
  },
  {
    "id": 18,
    "quantita": 3,
    "locazione": "Milano",
    "prezzo": 350000,
    "metri_quadri": 145,
    "tipo": "Appartamento",
    "numero_stanze": 6,
    "bagni": 3,
    "balcone": True,
    "anno_costruzione": 2019,
    "condominio": True,
    "piano": 5,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Appartamento spazioso e moderno.",
    "foto": "url_foto_18.jpg"
  },
  {
    "id": 19,
    "quantita": 2,
    "locazione": "Verona",
    "prezzo": 270000,
    "metri_quadri": 100,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2018,
    "condominio": False,
    "piano": 1,
    "ascensore": False,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento con ampi spazi.",
    "foto": "url_foto_19.jpg"
  },
  {
    "id": 20,
    "quantita": 3,
    "locazione": "Torino",
    "prezzo": 290000,
    "metri_quadri": 110,
    "tipo": "Appartamento",
    "numero_stanze": 5,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2021,
    "condominio": True,
    "piano": 3,
    "ascensore": True,
    "riscaldamento": "Autonomo",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": False,
    "giardino": False,
    "descrizione": "Appartamento in una zona centrale.",
    "foto": "url_foto_20.jpg"
  },
  {
    "id": 21,
    "quantita": 2,
    "locazione": "Bologna",
    "prezzo": 320000,
    "metri_quadri": 130,
    "tipo": "Appartamento",
    "numero_stanze": 4,
    "bagni": 2,
    "balcone": True,
    "anno_costruzione": 2020,
    "condominio": True,
    "piano": 4,
    "ascensore": True,
    "riscaldamento": "Centralizzato",
    "aria_condizionata": True,
    "cucina": "Cucina abitabile",
    "posto_auto": True,
    "giardino": False,
    "descrizione": "Appartamento moderno in zona centrale.",
    "foto": "url_foto_21.jpg"
  }
]
@app.route("/home")
def home():
    return "ciaone"

@app.route("/api/fgas/list", methods = ["GET"])
def getFgasList():
    #data = duplicate_array(data,200)
    return jsonify(data)

@app.route("/api/fgas/update", methods = ["POST"])
def updateFgasElement():
    item = Item.query.get(item_id)
    if not item:
        return jsonify({'message': 'Item not found'}), 404

    data = request.get_json()

    # Aggiorna solo i campi specificati nei dati della richiesta
    if 'name' in data:
        item.name = data['name']
    if 'quantity' in data:
        item.quantity = data['quantity']

    db.session.commit()

    return jsonify({'message': 'Item updated successfully'}), 200

def duplicate_array(original, target_length):
    if not isinstance(original, list):
        raise ValueError("L'input deve essere un array (lista).")
    result = []
    while len(result) < target_length:
        result.extend(original)
    return result[:target_length]



if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)